# Generated by Django 2.2.8 on 2020-04-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200426_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offerItemCategory',
        ),
        migrations.AddField(
            model_name='offer',
            name='offerItemCategory',
            field=models.ManyToManyField(blank=True, null=True, to='services.ItemCat'),
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offerVarient',
        ),
        migrations.AddField(
            model_name='offer',
            name='offerVarient',
            field=models.ManyToManyField(blank=True, null=True, to='services.Variant'),
        ),
    ]
