# Generated by Django 2.2.8 on 2020-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='itemcat',
            name='CatImg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
